### ISSUE TITLE
How to use/acess?

### ISSUE THREAD

**Issue by JolinM** [Daandelange/kirby3-simplestats#1]
Hi Daandelange, I’m quite interested by your plugin, but I’m a real n00b!

I followed the Installation method (`copy to /site/plugins/simplestats`), but now I’m stuck. How do I access the plugin? Do I need to go to my `Kirby panel`?

**Comment by Daandelange** [comment]
Hello, your plugin should be up & running.
- Any issues should be reported to `site/logs/simplestats_errors.txt`.
- The panel is for viewing the collected stats only. After 24h there should be something visible. You can also view the raw database file with an SQL viewer (`site/logs/simplestats.sqlite`).
- You can customise your setup up in `site/config/config.php` like any other kirby plugin. (available options to override are listed in `options.php`)

**Comment by JolinM** [comment]
Hi Daandelange, thanks for the quick support! It’s still a bit fuzzy for me, but I’ll wait 24h and see if something’s pops up.
Right now, I only have the plugin on my local installation (laravel valet). Is this a problem?

1. I don’t currently see the log `folder`.
![Capture d’écran, le 2021-01-15 à 11 53 25](https://user-images.githubusercontent.com/3504842/104755423-66352780-5728-11eb-970d-f678f8eacf47.png)

And in my panel, it is unclear where I should go to see the stats 🤔
![Capture d’écran, le 2021-01-15 à 11 53 12](https://user-images.githubusercontent.com/3504842/104755425-67665480-5728-11eb-8fbf-8aae450b0985.png)

**Comment by Daandelange** [comment]
![image](https://user-images.githubusercontent.com/1329784/104757887-e7f37800-575d-11eb-95d1-a7451293d009.png)
It should be in your site's main menu. If not, there might be something wrong...

**Comment by JolinM** [comment]
Oh! This is so easy! 🤦‍♂️

I have a new error message now 😬
![Capture d’écran, le 2021-01-15 à 13 37 06](https://user-images.githubusercontent.com/3504842/104765419-e06ca880-5736-11eb-8858-b3d488419eab.png)

**Comment by JolinM** [comment]
And on my remote install, this is the error message `Class 'SQLite3' not found`. 😔

**Comment by Daandelange** [comment]
For the Database issue, I'll try to reproduce it. Do your dev tools' network monitor reveal something more useful ? Is there something in `simplestats_errors.txt` ?
The 2nd one speaks for itself, you don't have SQLite3 enabled on your server. (worth looking if you can enable it trough `php.ini` or your hoster's admin panel)

**Comment by Daandelange** [comment]
There were some files missing for being plug-and play. Can you test with the latest version ?

**Comment by JolinM** [comment]
Hey Daandelange, I reinstalled with your new version.

Will look into activating 'QLite3 on the remote one.
Same error message on the local. Dev console says `[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (pagestats, line 0)`

**Comment by Daandelange** [comment]
I've tested the plugin on a fresh install, the latest version works on my side, but that's only 1 possible configuration.
If you're familiar with php code, you can [enable Kirby debugging](https://getkirby.com/docs/guide/troubleshooting/debugging) and trace back errors that don't appear in `site/logs/simplestats_errors.txt`.

**Comment by JolinM** [comment]
Hey there, I tried on a fresh install as well. Same error `Unable to open database: unable to open database file`.
And on both install, even with Kirby debugging, the logs folder is missing.

If it might help, I’m running my local version through the latest version of Valet. Don’t know if it’s relevant.

**Comment by Daandelange** [comment]
Did you try creating the logs folder ? (after which the db and log file should appear on visiting your website ?)
If not, the plugin is probably not able to load itself correctly in Kirby, maybe it's something to do with Valet.

**Comment by JolinM** [comment]
Bingo, got it. Now works on my local installation :)
There’s no stats, but I guess this is because it’s local, duh.
Got some error thought. I’ll let you know how it goes on my remote install as soon as I got SQLite on it.
[simplestats_errors.txt](https://github.com/Daandelange/kirby3-simplestats/files/5831607/simplestats_errors.txt)

**Comment by JolinM** [comment]
Hum, on dubious. On the remote, my hosting companies informed me SQlite 3 is in place, and the Terminal agrees.

![Capture d’écran, le 2021-01-18 à 12 13 27](https://user-images.githubusercontent.com/3504842/104945405-b27da300-5986-11eb-9086-f3fed46086fb.png)

**Comment by Daandelange** [comment]
The error in your logfile has just been fixed. (update simplestats)

As for SQLite3... that screenshot looks like the unix command line binary, what you need is the PHP Module.
You could try removing the `\` [here](https://github.com/Daandelange/kirby3-simplestats/blob/0dc54710f8d71b206627c1eca233cbfc4d34067f/src/models/SimpleStatsDb.php#L35).
Otherwise, as a temporary solution, upload the locally generated database to your online server, to bypass the SQLite3 requirement.

**Comment by JolinM** [comment]
With the new version and the upload of the `simplestats.sqlite` file, I have a new error!` could not find driver`

**Comment by Daandelange** [comment]
That seems to be related to Kirby's PDO/SQLITE driver used by this plugin.
[Maybe this thread can give you some directions.](https://forum.getkirby.com/t/how-to-debug-the-form-could-not-be-saved-exception-pdoexception-could-not-find-driver/17865/3) (look at `phpinfo()` if the PHP PDO SQLite3 module is enabled, and try to install that composer dependency)

**Comment by JolinM** [comment]
I’ll need a bit more help to go through these steps; it is quite confusing for me.
> 1. Add "ext-pdo_sqlite": "*" to my composer.json in the require block

We’re talking about the composer.json file located on the `kirby` folder, right?

> 2. Run composer update to update the composer.lock file

I don’t know how to do that

> 3. Deploy
It’s already deployed if it’s on my remote (FTP) server, right?

**Comment by Daandelange** [comment]
1. No, the [one in the plugin folder](https://github.com/Daandelange/kirby3-simplestats/blob/0dc54710f8d71b206627c1eca233cbfc4d34067f/composer.json#L20-L24).
When you then run the composer update, it will update the plugin filles and make the necessary changes to integrate that extra dependency.
So you might need to re-upload the plugin files after that. Refer to the [Kirby Composer Guide](https://getkirby.com/docs/cookbook/setup/composer) for more detailed instructions.

**Comment by JolinM** [comment]
Got it, thanks for the steps. Same error on my remote install :/

**Comment by Daandelange** [comment]
I've just updated the plugin, including a draft of a requirements checker in the Information tab (panel).
Could you check if all requirements are there ? Hopefully that gives a better insight.

**Comment by JolinM** [comment]
Works great on the local instal. On the remote one, it shows nothing :(
![Capture d’écran, le 2021-01-21 à 12 32 02](https://user-images.githubusercontent.com/3504842/105388523-c292be00-5be4-11eb-8dc0-15ec0dfd19b5.png)

**Comment by Daandelange** [comment]
Does it show anything useful on `website.domain/api/simplestats/listdbinfo?csrf=YOURTOKEN` ? (you need to set the CSRF in your config.php : `'api.csrf' => 'YOURTOKEN',`)

**Comment by JolinM** [comment]
`{"status":"error","message":"could not find driver","code":500,"key":null,"details":[]}`

**Comment by Daandelange** [comment]
Hmm, ok, probably the `Kirby\Database\Database` class that doesn't work in your configuration.
I've made the requirements check "autonomous", so it should work now. Please check the message in the panel again, or `website.domain/api/simplestats/checkrequirements?csrf=YOURTOKEN`.

**Comment by JolinM** [comment]
New error. the pop out when I open the page in the panel says
`Return value of daandelange\SimpleStats\SimpleStatsDb::database() must be an instance of Kirby\Database\Database, null returned`

Database Requirements says
`PHP Extensions=Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mysqlnd, odbc, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, xmlreader, xmlrpc --- PHP=OK --- SQLite3=ERROR --- SQLite3.try=ERROR Class 'SQLite3' not found --- CreateDB()=ERROR:could not find driver --- pdo_sqlite=ERROR --- sqlite3=ERROR`

And the url `https://www.jolinmasson.com/api/simplestats/checkrequirements?csrf=COUCOU`  says
`{"dbRequirements":"PHP Extensions=Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mysqlnd, odbc, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, xmlreader, xmlrpc --- PHP=OK --- SQLite3=ERROR --- SQLite3.try=ERROR Class 'SQLite3' not found --- CreateDB()=ERROR:could not find driver --- pdo_sqlite=ERROR --- sqlite3=ERROR"}`

**Comment by Daandelange** [comment]
Ok, thanks, so that clarifies a lot. They say the same thing : Your php extensions `sqlite3` (for SQLite3) and `pdo_sqlite` (used by `Kirby\Database\Database`) are not available. And they are at the core of this plugin. IMO, the easiest solution would be porting SimpleStats to optionally use MySQL databases (which seem to be enabled on your host) instead of SQLite3; but that is out of my scope... but I can give some directions for such changes if you wish.
Of course, a very simple solution would be to ask your hoster to enable them, or enable them yourself if you have access to custom `php.ini` or via your hoster's site admin panel. Or change your hoster.

**Comment by JolinM** [comment]
My host replied me that! Does it help?

```
While checking through your concern, The sqlite3 is installed manually on the server.

Please check the same from your end,

++++++++++++++

root@golf [~]# sqlite3
SQLite version 3.6.20
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> 

```

**Comment by JolinM** [comment]
I indeed ran the command in ter Remote terminal, and it does seams to be installed.
![Capture d’écran, le 2021-01-28 à 18 02 40](https://user-images.githubusercontent.com/3504842/106209520-2c860700-6193-11eb-8ed0-966a803ccaba.png)
My domain is a secondary domain on my host. Could that be what causes the problem?

**Comment by Daandelange** [comment]
Hello, yes, the **command line** sqlite3 is installed, but the **PHP module** with the same name is probably not, as it's not listed in your "PHP extensions", neither is "pdo_sqlite". You need to enable the PHP module.
This one --> https://www.php.net/manual/en/class.sqlite3.php

**Comment by JolinM** [comment]
They say it’s already installed 😑.
![Capture d’écran, le 2021-01-29 à 14 08 14](https://user-images.githubusercontent.com/3504842/106316909-79251d00-623b-11eb-9cb9-9f75dd1e598e.png)

**Comment by Daandelange** [comment]
Well, then something weird is happening on your host, it's not enabled on your Kirby installation.  
In the panel's simplestats requirement check, the extensions that your Kirby php installation can use are listed after `PHP Extensions=**your**extensions**`, so then you might need to compare the output of `php -m` and the list in the panel. If they differ, your server setup is using a different PHP environment then the one in the console. Try creating an `info.php` (with `<?php phpinfo(INFO_MODULES); ?>`) file in your Kirby root and compare the extensions listed there.

**Comment by JolinM** [comment]
Here’s my [info.php](https://www.jolinmasson.com/documents/info.php)
I tried to 'activate' sqlite by adding these three lines at the end of my php.ini, but it made my site crash (I have not a lot of clue about what I’m doing actually 😑)
.
`extension=curl
extension=pdo_sqlite
extension=sqlite3`

The output of the console and the site don’t match :/
[SimpleStats output.txt](https://github.com/Daandelange/kirby3-simplestats/files/5896165/SimpleStats.output.txt)
[Terminal server.txt](https://github.com/Daandelange/kirby3-simplestats/files/5896166/Terminal.server.txt)

**Comment by Daandelange** [comment]
Yes, that's the regular way to go. A crash means it doesn't accept your new lines it's very strict. Sometimes you need to add `.so` (or `.dll` on WIN). Try them one by one until it works, search online, or ask your hoster for support on how to enable it, read their FAQ.

**Comment by JolinM** [comment]
Ooooof, I asked to activate the extension… so they switched my PHP to 5.6, breaking my site in the process. 😑 I asked a second time, and they reverted to 7.3 and activated the extension. It now works like a charm!

Geez, that was not so complicated, and entirely on their end. Thanks a lot Daandelange for the support during all this process!

**Comment by Daandelange** [comment]
You're welcome, I'm happy it works now. :)

**Comment by JolinM** [comment]
Hey Maandenlange, I think I’m cursed. I did a clean install of the plugin + database last weekend, now that I have the requirements.
I used a VPN to visit my website, see if it worked, and 48 hours, I still have no stats 😭.
Any clue?
![Capture d’écran, le 2021-02-09 à 17 51 54](https://user-images.githubusercontent.com/3504842/107439074-81b10980-6aff-11eb-86d7-7add48fe0d99.png)

**Comment by Daandelange** [comment]
Hey Jolin, I guess that you're not connected to the panel using your VPN ?
Is the logfile empty ? Did you try deleting the db file and let it create a new one ? (looks like it's already the case, but you never know...)
Don't bother waiting 24/48H : If there's nothing in this view ( cf: `No rows available`), nothing will appear later.
Did you try if referrer tracking works (instantly appears) ?
Any other clue... try disabling the Kirby cache or other settings that could affect tracking ? (Try a clean plainkit/starterkit on your configuration?)
