### ISSUE TITLE
Add support for composer

### ISSUE THREAD

**Issue by MaluNoPeleke** [Daandelange/kirby3-simplestats#13]
Can you please add support for composer?
It is offered by nearly all plugins and makes updating them very easy.

**Comment by Daandelange** [comment]
Hey, There already is a composer file which loads some php components and makes updating easy.
Do you mean to publish it in the composer database so it can become a dependency ? I've never done such a thing but I can give it a shot. Any directions ?

**Comment by MaluNoPeleke** [comment]
It works but on packagist it says "This package is not auto-updated.". Does it mean that new updates won't be automatically available via composer? I haven't seen this with other pluigns.

**Comment by Daandelange** [comment]
As I understand it, I have to link my Github account to enable automatic updates. (I prefer not to)
But a semi-automatic mechanism is crawling the repo once a week, grabbing new github releases; plus I can manually hit an "Update now" button if needed; so to me this is not an issue. (The warning seems a bit "big".)

**Comment by MaluNoPeleke** [comment]
Okay, thanks for the explanation

**Comment by MaluNoPeleke** [comment]
Sorry, I installed it without specifying the kirby-3.6 branch in composer so that it was the incompatible version 0.3.1
