### ISSUE TITLE
authorizedRoles not working properly

### ISSUE THREAD

**Issue by hannesherold** [Daandelange/kirby3-simplestats#16]
## Description
The option `authorizedRoles` seems not to work properly. With the option set to `admin` for example, SimpleStats is still fully accessible for `editor` users. Only the option `dismissDisclaimer => true` set in `site/config/config.php` is ignored, meaning that the disclaimer dows show for editors.

**Expected behavior**  
For unauthorized roles, SimpleStats should not be visible in the Panel menu.

## My setup
Plainkit Kirby 3.6.1.1

**Console output**  
```
code: 403
details: Array []
exception: "Kirby\\Exception\\PermissionException"
file: "api.php"
key: "error.permission"
line: 331
message: "You are not authorised to upgrade the db file."
route: "simplestats/mainview"
status: "error"
<prototype>: Object { … }
index.js:1:6814
```
```
code: 403
details: Array []
exception: "Kirby\\Exception\\PermissionException"
file: "api.php"
key: "error.permission"
line: 58
message: "You are not authorised to view statistics."
route: "simplestats/pagestats"
status: "error"
<prototype>: Object { … }
index.js:1:6814
```

**My system**
 - Device: MacBook Pro 2019
 - OS: MacOS Monterey 12.0.1
 - Browser: Opera 82, Firefox 95

**Comment by Daandelange** [comment]
I've very quickly implemented a protection method which is indeed unpolished.
The PermissionExceptions are seemingly  correctly working, preventing data from being visible to unauthorized users.
Just the "interface hiding part" remains to be done.

Feel free to submit a PR or I'll polish this later.

**Comment by Daandelange** [comment]
It's not in the menu anymore, but there's still some roles polishing/checking to do, I'll consider this "bug" fixed.
Feel free to comment in #29 for permission-related feature requests.
