### ISSUE TITLE
UI Conflict with Pagetable plugin

### ISSUE THREAD

**Issue by hannesherold** [Daandelange/kirby3-simplestats#20]
When using SimpleStats together with Pagetable plugin by sylvainjule (https://github.com/sylvainjule/kirby-pagetable), the UI of pagetable gets compromised in the panel.

Kirby 3.6.1.1 Plainkit with SimpleStats and Pagetable:

![simplestat-active](https://user-images.githubusercontent.com/46819942/146676067-a6ff9f15-20e7-4574-92e6-2a540074836c.jpg)

Without SimpleStats:

![simplestats-deactivated](https://user-images.githubusercontent.com/46819942/146676085-17dd4f31-087e-45f5-9fc9-84fe28db6b84.jpg)

**My system**

- Device: MacBook Pro 2019
- OS: MacOS Monterey 12.0.1
- Browser: Opera 82, Firefox 95
- Kirby 3.6.1.1
- Pagetable Plugin 1.0.1

**Comment by hannesherold** [comment]
Thank you for your quick reaction (and the new beta release)! Odd that you cannot reproduce the issue. I'm using plainkit and latest plugin versions.

I haven't had much time today but quickly tested the new `0.4.6-beta`. The layout bug has changed, now the pagetable section looks like this:

![Bildschirmfoto 2021-12-20 um 15 29 44](https://user-images.githubusercontent.com/46819942/146834910-df811e42-3705-4cc0-b6f6-8a2e2067d1fe.png)

So the section title and icons look all right, but the footer element still is compromised. It uses the class `.vgt-wrap__footer`. Here it is with simplestats plugin running:

<img width="1040" alt="Bildschirmfoto 2021-12-20 um 15 28 51" src="https://user-images.githubusercontent.com/46819942/146835123-accb086a-f73d-4df8-879e-d384bdcb2f83.png">

And here without:

<img width="1040" alt="Bildschirmfoto 2021-12-20 um 15 29 03" src="https://user-images.githubusercontent.com/46819942/146835152-a6984f3e-a728-4e04-884e-a3f8ee55d0f9.png">

This is what I found real quick. Maybe it helps a bit? Sorry that I can't contribute more just now.

**Comment by Daandelange** [comment]
That perfectly helps, thanks, I'll figure it out :)
