### ISSUE TITLE
Feature request: option to exclude bots

### ISSUE THREAD

**Issue by MaluNoPeleke** [Daandelange/kirby3-simplestats#21]
I really like this plugin but I am not so much interested in the bots data. Could you add an option in the panel or in the config to toggle bots data in the visualizations?

**Comment by Daandelange** [comment]
Thanks :)
Why not, sounds good, with a little work it could even be excluded from the database to keep that minimal too.

**Comment by MaluNoPeleke** [comment]
Looking forward to it, thanks for the quick reaction. I even found a very similar idea already mentioned in the [options.php](https://github.com/Daandelange/kirby3-simplestats/blob/f3bfbbe013747fe3038168d61a1da1efbe087833/src/config/options.php#L57).

**Comment by Daandelange** [comment]
There you go, there's now an option to hide the current bots data and to prevent collecting more.

**Comment by MaluNoPeleke** [comment]
Thanks a lot. I would like to give it a try but composer is showing an error message while installing:

> Class daandelange\SimpleStats\SimplestatsTrackingMode located in ./site/plugins/simplestats/src/models/SimpleStatsTrackingMode.php does not comply with psr-4 autoloading standard. Skipping.

Can you please fix that?

**Comment by Daandelange** [comment]
Oops, that should fix it, thanks.

**Comment by MaluNoPeleke** [comment]
Thanks for the quick response. I need to wait until it is "visible" on packagist and will then update.

**Comment by MaluNoPeleke** [comment]
Can you please push an update to packagist?

**Comment by Daandelange** [comment]
Done, but you'll have to use `dev-master`, no version bump yet.

**Comment by MaluNoPeleke** [comment]
Great, works as desired, thank you!
