### ISSUE TITLE
[Documentation] Composer installation according to docs fails

### ISSUE THREAD

**Issue by iocouto** [Daandelange/kirby3-simplestats#25]
Right now, because SimpleStats does not have a 'stable' release tag, when we try to follow the simple installation instructions for composer, the installation fails - because the latest versions of composer assume by default that we always want to install the latest STABLE version of a package. If a package has NO stable version, then installation fails with a warning:

<img width="647" alt="Screen Shot 2022-02-25 at 4 07 36 pm" src="https://user-images.githubusercontent.com/75245963/155657557-fe6ab67a-99bf-4daa-8d46-da946a139c81.png">

In order to be able to install with composer, at the moment it's necessary to explicitly specify a 'beta' compatibility - e.g.:

``` sh
composer require daandelange/simplestats:~0.4-beta
```

**Comment by Daandelange** [comment]
Thanks for the notice, I'm still new to working Composer ! :)
