### ISSUE TITLE
How to "enable" tracking^^

### ISSUE THREAD

**Issue by j54j6** [Daandelange/kirby3-simplestats#34]
Hey, 

I am not sure if my installation is the problem or I didn't understand the Documentation...

I want to track my blog sites and added the Page method "$page->simpleStatsImage()" to the header of my template so every time the page is called this code will be executed... But my tracking charts are all empty just the list on the information page is filled with 2 entries "Visitors (current session)"

The Setup checker doesn't give any warnings (see SC) - did I need to use the singeltons to? and what is the "OnImage" tracking method? - is there another documentation site for this plugin and I overread it?^^

This is my current Information Page:

![information](https://user-images.githubusercontent.com/24981307/224421537-2001be3e-ec7e-4521-911f-73781c99387a.PNG)

And all other pages looks like this (from the avail. data perspektive ^^)
![allother](https://user-images.githubusercontent.com/24981307/224421597-b18efcb1-abb0-46ae-ab65-e3ecdb5f5e34.PNG)

This is my header code (snippet):
```
<body data-bs-theme="light">
    <header>
      <?php $page->simpleStatsImage() ?>
      <nav class="navbar navbar-expand-md">
        <div class="container-fluid">
```

I've tried to use the Singletons too but I only get an error (I don't know what Libary I need to import ^^) 

Hope that somebody can help me :)

**Comment by Daandelange** [comment]
Hi,
1. Regarding the "empty stats", this is normal : unique visitors are collected over 24H timespans; after which they are converted to stats and deleted. You'll see your `Visitors (current session)` "moving" into the stats after 24H.
2. Tracking method:  
    - I just realised that there's no section about setting up tracking in the readme, I'll add something.  
    - Currently only `SimplestatsTrackingMode::OnLoad` has been tested (via the route API so that it works with caching). I gave the way you're requesting a shot a while ago, but haven't been able to fully test it.
    As you guessed, the intended way is to set`tracking.method = SimplestatsTrackingMode:: OnImage;` to "unlock" `$page->simpleStatsImage()` (you can check if it echos an `<img>` tag, the `src=""` should not be 404).   
    Note that the 2 visits that populated your DB are probably from the `OnLoad` tracking method (if you didn't change it), you can erase the db file and start over to see if your db gets populated again using `OnImage`.

**Comment by j54j6** [comment]
Hey :) 

Thanks a lot for your fast reply. I've tried to get this running the last days but without any success. 

If I use $page->simpleStatsImage() in my header (HTML) there comes nothing. Using echo($page->simpleStatsImage()) also doesn't return anything... - Did I need to include something?
Oh if I use var_dump on this function it returns "null"... - using other functions like my "title()" this will return the correct object^^


Another thing is that I get an error when entering my panel with the following message: 
![noVisitsovertime](https://user-images.githubusercontent.com/24981307/224773287-b48c1205-4dd6-491e-95d9-9eac6bb1fb5a.PNG)

I think this is because there are no statistics yet and the variable is not existent?

**Comment by j54j6** [comment]
Okay, I solved the problem. 
Originally I've installed the plugin like in Version one (Drop the folder in the Plugins folder of kirby)... Now I removed this folder and only used "composer require daandelange/simplestats:~0.6.1-beta" - Works like a charm... almost instantly my data site is filled with OS Versions... This seems to work now, but my configurtion is not used (config/config.php)

![sc](https://user-images.githubusercontent.com/24981307/224781210-fe859995-170f-4b45-8116-3a9f9daf8396.PNG)

The DB was reused and worked properly but the "Track unique users every" value and I guess also my salt is not my own :/

**Comment by Daandelange** [comment]
1. `tracking.uniqueSeconds` not `uniqueSeconds`. ;)
2. Salt is not shown, it looks "On" (why is it written `an`?), so the setting is correct. *(Does it turn off if you don't set the salt in your config?)*
3. `e.visitsOvertime` (screenshot) --> An UI error that I have to fix when the db is still empty. Should not prevent working once there's data.

After that it should work as expected, i hope.

**Comment by j54j6** [comment]
Hey :) 

Again I am pleased that you respond so fast :) -

1. Yes this works ^^ - In the last version I've used the seconds were correct with the last setting - curious ^^ - But in the end this was a simple fix :D 
2. The salt is overpainted :) - It is written "an" because of the language setting (I'm from Germany and build my Panel multilingual (English and German - I simply forgot to change this ^^)
3. I marked a previous comment as "outdated" I thought that the 
plugin works but the time I recreated the Database no new data are arrived and the <?php echo($page->simplestatsimage()); ?> still returns nothing on my inspector 
Here is a Screenshot - If i dump this there is still only "null"

![sc23](https://user-images.githubusercontent.com/24981307/224817375-1ff05793-2115-4db5-a996-a16390016738.PNG)

Thank you <3

**Comment by Daandelange** [comment]
Hmm, looks like a recent Kirby update broke the `simpleStatsImage` page method... As a quick-fix, you can try printing the image yourselve [like this](https://github.com/Daandelange/kirby3-simplestats/blob/222d80eb7decbd943881a65814b1959674fa15cd/src/config/pagemethods.php#L24-L38) instead of calling the function.  
It's weird though that you get a `Cms/Field`, are you sure that you call `$page->simpleStatsImage()` ? Kirby usually returns an empty field when the requested method doesn't exist on the page object. You should get a `Toolkit\Html`.

**Comment by j54j6** [comment]
Yes, if I call only "$page->simpleStatsImage()" - it returns "NULL" 
I tried tto use all lower and all uppercase writing to prevent any writing error :) - Compare the last picture to the initial code snippet post :) 

As comparison in the following I call the function with the correct writing again:
![24](https://user-images.githubusercontent.com/24981307/224919190-4475ef21-542e-4ab6-953e-657408b6aba1.PNG)

Please notice that the "NULL" is a result of the var_dump - The function doesn't exist in my installation ^^

I'll try to add the Image like described in your link ^^

**Comment by j54j6** [comment]
Again, thanks a lot! (You should post a Patreon link or a coffee link here. I would love to honor your work.)

I looked up the code a bit, and the second I opened the 'pagemethods' site, I saw this:

![pagemethods](https://user-images.githubusercontent.com/24981307/225065526-49ef46d5-c89e-4c78-a506-3e0f9265c05c.PNG)

This doesn't look right to me ^^ - if I replace the first check with your comment "// Correct tracking method?" to "SimpleStatsTrackingMode::OnImage === option('daandelange.simplestats.tracking.method', SimpleStatsTrackingMode::OnImage)" -> OnLoad is changed to "OnImage," and I modified my config with the numeric value from your SimpleStatsTrackingMode.php file. The code is now like in your hooks.php file:

The Code is now like in your hooks.php file
![hooks](https://user-images.githubusercontent.com/24981307/225065803-a9826eb6-51d4-45d2-968f-fe4a9addc34a.PNG)


```
const OnLoad   = 0; // Default. When the kirby router routes to a page, tracking happens. (all views are tracked, but pageload time increases a bit).
    const OnImage  = 2; // Provides a dummy image for each page, which you have to display in your html using $page->simpleStatsImage(). Tracking happens when the image is loaded (delayed).
    const Disabled = 3; // Any tracking / processing is disabled, viewing remains possible.
    const Manual   = 4;
```

Then it works like a charm :) - I guess this was unintentional? Whatever, I also see some stats on the Pagevisits page (not all tables are filled, but I guess this is intentional? - I set the 'uniqueSeconds' interval to 10 for this test.

I also used your testing tool on the information page (thanks a lot for this <3 ^^), and there is some data:
![pages](https://user-images.githubusercontent.com/24981307/225065368-3401c93e-0d29-4c8b-afc3-090844a0c49e.PNG)

I forked your repository and updated the "README" file and the 'pagemethods' file... If you like, you can merge it - be aware that I only tested this on my Kirby installation (newest).

I also wanted to add a "Current Simplestats Version" field to the information site (under Version History or behind the heading), but Vue is really not my thing ^^

**Comment by Daandelange** [comment]
Awesome, thanks for initiating this PR. Yes it is a mistake.
> (not all tables are filled, but I guess this is intentional? - I set the 'uniqueSeconds' interval to 10 for this test.
In LineCharts, I think you need 2 time periods (or frames) to see data (controlled by the timespanutility setting), so lines are drawn in-between. This an be considered a visual bug, but I'm also not sure how to work around. And yes, `uniqueSeconds` controls syncing delay to the charts.

Coffee...  thanks for your interest in helping out and your kind words, I'm figuring out how to do this legally but: French laws... :/ .
Anyways, while money is encouraging too, I definitely prefer to take PRs as yours above; my wish/hope is that SimpleStats becomes community-managed. :)
Good idea for the version info, I can have a look to spare you the Vue nightmares :p

**Comment by j54j6** [comment]
Using `'tracking.method' => SimplestatsTrackingMode::OnImage,` does not work for me - then I need to import the file to my Config I guess with the "include" statement or is there a kirby specific thing?

Here you see the error: (Undefined type 'SimplestatsTrackingMode')
![25](https://user-images.githubusercontent.com/24981307/225087951-41e05299-d039-43b6-bc0c-9e8aaeb40836.PNG)

**Comment by j54j6** [comment]
The namespace was missing ^^ - seems like the config does not recognize any namespaces ^^

Correct is: 
use daandelange\SimpleStats\SimpleStatsTrackingMode;

then you can use  'tracking.method' => SimpleStatsTrackingMode::OnImage,

Pull Request is updated :)

**Comment by j54j6** [comment]
Tracking is now working - Merge Completed 

If there are any other problems with onImage Tracking I will reopen this issue or add a new one if needed. 

Thank you ^^
