### ISSUE TITLE
Bug when login as unknown user role

### ISSUE THREAD

**Issue by Daandelange** [Daandelange/kirby3-simplestats#37]
According to [this topic](https://forum.getkirby.com/t/loggin-in-as-editor-throws-panel-area-error/27679) there's a bug when you login as a non-registered user-role in the options.

As a temporary work around, register any custom user role in the simplestats options.

**Comment by CHE1RON** [comment]
Just FYI: when I tried yesterday, adding roles to `authorizedRoles` did not solve the error.
