### ISSUE TITLE
Broken timeline

### ISSUE THREAD

**Issue by bogdancondorachi** [Daandelange/kirby3-simplestats#42]
Hi, I've added the simplestats plugin 5 day's ago on (18-09-2023) and for some reason the page visits timeline is stuck at (01-09-2023)

![image](https://github.com/Daandelange/kirby3-simplestats/assets/39380741/a4b720d4-f347-4c23-8804-367baad4f044)
![image](https://github.com/Daandelange/kirby3-simplestats/assets/39380741/250929f6-3d4a-4bc0-8e1d-32d418dd4d31)

Running Kirby 3.9.6.1 and plugin version 0.6.3-beta

**Comment by Daandelange** [comment]
Hey, That looks like normal behaviour to me, SimpleStats uses a timespan of 1 week by default. ;)

**Comment by bogdancondorachi** [comment]
Oh, that makes totally sense now, my bad. Thanks for the quick response 👍

**Comment by bogdancondorachi** [comment]
Oh, that makes totally sense now, my bad. Thanks for the quick response 👍
