### ISSUE TITLE
JavaScript tracking script to bust CDN cache

### ISSUE THREAD

**Issue by miragecraft** [Daandelange/kirby3-simplestats#43]
Right now my site sits behind Cloudflare CDN that do page caching which means if you hit the cache you aren't hitting Kirby thus SimpleStats won't register the visit.

It would be very useful have a companion JavaScript file that can talk to SimpleStats and *punch through* CDN caching.

**Comment by Daandelange** [comment]
Hi, I have never worked with cloudflare cache, but good catch !

Why JS ? Isn't the pixel tracking OK ?
What exactly would you need on the simplestats side ? A JS asset to load with a function to call from your `<body>`, like G.Analytics or Matomo ?
What is a punch-trough ?

**Comment by miragecraft** [comment]
By “punch-through” I simply mean get past caching without being affected.

Would tracking pixels have fixed src URLs (esp. the query string) or would it change for each visitor/visit?

Since the src URL is stored on the page, caching would effectively “freeze it” in place

If the src URL is fixed then I could set up rule(s) for Cloudflare to not cache the pixel image, and JavaScript would indeed not be needed.

Otherwise JavaScript would be needed to generate the necessary URL.

> Isn't the pixel tracking OK ?

By “the pixel tracking”, does SimpleStats currently use tracking pixel? I wasn’t aware that it is.

**Comment by Daandelange** [comment]
Yes, the pixel is implemented and they have a per-page URL, the image never changes but the HTTP response is set not to be cached. We don't need JS execution for retrieving more data. (But now that I think of it, I don't know if referrer tracking works correctly like that!)  Alternatively, js tracking could become a new tracking method / feature.  
Refer to [Setup/Integrating to your page in the readme](https://github.com/Daandelange/kirby3-simplestats?tab=readme-ov-file#integrating-to-your-page) to enable pixel tracking. (look at the tracking method)

**Comment by miragecraft** [comment]
Got it, I’ll check it out.
