### ISSUE TITLE
Column "medium" is not created in table "referrers"

### ISSUE THREAD

**Issue by medienbaecker** [Daandelange/kirby3-simplestats#9]
First of all, thanks for this great plugin. I think it fits really nicely into the Kirby mindset 👍 

I noticed my website did not track any referrers so I had a look at `simplestats_errors.txt` and saw hundreds of messages like `General error: 1 table referrers has no column named medium`. After editing the SQLite database and adding a `medium` column to the database it started working. 

You'll probably have to add this to [this line](https://github.com/Daandelange/kirby3-simplestats/blob/eb58f05293c6fab105d1d1fc9175a45c3656d3da/src/models/SimpleStatsDb.php#L38).

**Comment by Daandelange** [comment]
Hello, Thanks :)
Indeed, I forgot to add it. Thanks for the PR too. :)
